# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'akademisyen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_akademisyen(object):
    def setupUi(self, Form_akademisyen):
        Form_akademisyen.setObjectName("Form_akademisyen")
        Form_akademisyen.resize(1594, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/amasyauniico/amasyauni.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_akademisyen.setWindowIcon(icon)
        Form_akademisyen.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(207, 207, 207);")
        self.groupBox_anamenu = QtWidgets.QGroupBox(Form_akademisyen)
        self.groupBox_anamenu.setGeometry(QtCore.QRect(350, 0, 1241, 1000))
        self.groupBox_anamenu.setTitle("")
        self.groupBox_anamenu.setObjectName("groupBox_anamenu")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_anamenu)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1231, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_verilendersler = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_verilendersler.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_verilendersler.sizePolicy().hasHeightForWidth())
        self.pushButton_verilendersler.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_verilendersler.setFont(font)
        self.pushButton_verilendersler.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 206, 209);\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222222; /* Daha koyu gri tonu */\n"
"    text-align: top; /* Metni üste hizala */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/dersler/dersler2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_verilendersler.setIcon(icon1)
        self.pushButton_verilendersler.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_verilendersler.setObjectName("pushButton_verilendersler")
        self.horizontalLayout.addWidget(self.pushButton_verilendersler)
        self.pushButton_dersgorenogrenc = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_dersgorenogrenc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dersgorenogrenc.sizePolicy().hasHeightForWidth())
        self.pushButton_dersgorenogrenc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_dersgorenogrenc.setFont(font)
        self.pushButton_dersgorenogrenc.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 206, 209);\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222222; /* Daha koyu gri tonu */\n"
"    text-align: top; /* Metni üste hizala */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/user/user2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dersgorenogrenc.setIcon(icon2)
        self.pushButton_dersgorenogrenc.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_dersgorenogrenc.setObjectName("pushButton_dersgorenogrenc")
        self.horizontalLayout.addWidget(self.pushButton_dersgorenogrenc)
        self.pushButton_ogrtemail = QtWidgets.QPushButton(self.groupBox_anamenu)
        self.pushButton_ogrtemail.setEnabled(False)
        self.pushButton_ogrtemail.setGeometry(QtCore.QRect(240, 420, 441, 61))
        self.pushButton_ogrtemail.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Arka planı şeffaf yapar */\n"
"    border: 1px solid #ccc; /* Kenarlık ekler ve kenar rengini belirler */\n"
"    border-radius: 10px; /* Köşeleri yuvarlar */\n"
"    padding: 1px 40px 1px 20px; /* İçerik ve kenar arasındaki boşluğu belirler */\n"
"    font-size: 19px; /* Yazı fontunun boyutunu belirler */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #555; /* Yazı rengini belirler */\n"
"    text-align: left; /* Metni ve ikonu sola hizalar */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    margin-left: 0; /* İkonu en soldan başlatır */\n"
"}\n"
"\n"
"QPushButton::text {\n"
"    padding-left: 0; /* Metni en soldan başlatır */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/posta/posta.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ogrtemail.setIcon(icon3)
        self.pushButton_ogrtemail.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_ogrtemail.setObjectName("pushButton_ogrtemail")
        self.pushButton_ogrtakademisyennumara = QtWidgets.QPushButton(self.groupBox_anamenu)
        self.pushButton_ogrtakademisyennumara.setEnabled(False)
        self.pushButton_ogrtakademisyennumara.setGeometry(QtCore.QRect(240, 350, 441, 61))
        self.pushButton_ogrtakademisyennumara.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Arka planı şeffaf yapar */\n"
"    border: 1px solid #ccc; /* Kenarlık ekler ve kenar rengini belirler */\n"
"    border-radius: 10px; /* Köşeleri yuvarlar */\n"
"    padding: 1px 40px 1px 20px; /* İçerik ve kenar arasındaki boşluğu belirler */\n"
"    font-size: 19px; /* Yazı fontunun boyutunu belirler */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #555; /* Yazı rengini belirler */\n"
"    text-align: left; /* Metni ve ikonu sola hizalar */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    margin-left: 0; /* İkonu en soldan başlatır */\n"
"}\n"
"\n"
"QPushButton::text {\n"
"    padding-left: 0; /* Metni en soldan başlatır */\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/numara/numara.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ogrtakademisyennumara.setIcon(icon4)
        self.pushButton_ogrtakademisyennumara.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_ogrtakademisyennumara.setObjectName("pushButton_ogrtakademisyennumara")
        self.label_profil = QtWidgets.QLabel(self.groupBox_anamenu)
        self.label_profil.setGeometry(QtCore.QRect(40, 250, 1191, 321))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_profil.setFont(font)
        self.label_profil.setStyleSheet("QLabel {\n"
"    color: #666; /* Yazı rengini değiştirerek açık gri tonuna ayarlar */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_profil.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_profil.setObjectName("label_profil")
        self.pushButton_ogrtfakulte = QtWidgets.QPushButton(self.groupBox_anamenu)
        self.pushButton_ogrtfakulte.setEnabled(False)
        self.pushButton_ogrtfakulte.setGeometry(QtCore.QRect(240, 490, 441, 61))
        self.pushButton_ogrtfakulte.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Arka planı şeffaf yapar */\n"
"    border: 1px solid #ccc; /* Kenarlık ekler ve kenar rengini belirler */\n"
"    border-radius: 10px; /* Köşeleri yuvarlar */\n"
"    padding: 1px 40px 1px 20px; /* İçerik ve kenar arasındaki boşluğu belirler */\n"
"    font-size: 19px; /* Yazı fontunun boyutunu belirler */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #555; /* Yazı rengini belirler */\n"
"    text-align: left; /* Metni ve ikonu sola hizalar */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    margin-left: 0; /* İkonu en soldan başlatır */\n"
"}\n"
"\n"
"QPushButton::text {\n"
"    padding-left: 0; /* Metni en soldan başlatır */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/konum/konum.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ogrtfakulte.setIcon(icon5)
        self.pushButton_ogrtfakulte.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_ogrtfakulte.setObjectName("pushButton_ogrtfakulte")
        self.pushButton_ogrtisimsoyisim = QtWidgets.QPushButton(self.groupBox_anamenu)
        self.pushButton_ogrtisimsoyisim.setEnabled(False)
        self.pushButton_ogrtisimsoyisim.setGeometry(QtCore.QRect(240, 280, 441, 61))
        self.pushButton_ogrtisimsoyisim.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Arka planı şeffaf yapar */\n"
"    border: 1px solid #ccc; /* Kenarlık ekler ve kenar rengini belirler */\n"
"    border-radius: 10px; /* Köşeleri yuvarlar */\n"
"    padding: 1px 40px 1px 20px; /* İçerik ve kenar arasındaki boşluğu belirler */\n"
"    font-size: 19px; /* Yazı fontunun boyutunu belirler */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #555; /* Yazı rengini belirler */\n"
"    text-align: left; /* Metni ve ikonu sola hizalar */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    margin-left: 0; /* İkonu en soldan başlatır */\n"
"}\n"
"\n"
"QPushButton::text {\n"
"    padding-left: 0; /* Metni en soldan başlatır */\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/user/user.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ogrtisimsoyisim.setIcon(icon6)
        self.pushButton_ogrtisimsoyisim.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_ogrtisimsoyisim.setObjectName("pushButton_ogrtisimsoyisim")
        self.label_ogrtphoto = QtWidgets.QLabel(self.groupBox_anamenu)
        self.label_ogrtphoto.setGeometry(QtCore.QRect(60, 300, 151, 151))
        self.label_ogrtphoto.setStyleSheet("QLabel {\n"
"    background-color: rgb(172, 172, 172);\n"
"    image: url(:/unknown/Unknown_person.jpg);\n"
"    border-radius: 10px; /* Köşeleri daha yuvarlak yapar */\n"
"    border: 2px solid #a9a9a9; /* Kenarlık rengi ve kalınlığını belirler */\n"
"    padding: 10px; /* Yazı içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 15px; /* Yazı fontunun boyutunu belirler */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #333; /* Yazı rengini belirler */\n"
"    background-color: rgba(255, 255, 255, 0); /* Arka plan rengini şeffaf yapar */\n"
"}\n"
"")
        self.label_ogrtphoto.setText("")
        self.label_ogrtphoto.setObjectName("label_ogrtphoto")
        self.label_profilsar_3 = QtWidgets.QLabel(self.groupBox_anamenu)
        self.label_profilsar_3.setGeometry(QtCore.QRect(20, 250, 21, 321))
        self.label_profilsar_3.setStyleSheet("background-color: rgb(255, 215, 0);\n"
"border-image: url(:/arkaplan/ic_arkaplan.jpg);")
        self.label_profilsar_3.setText("")
        self.label_profilsar_3.setObjectName("label_profilsar_3")
        self.label_profil.raise_()
        self.horizontalLayoutWidget.raise_()
        self.pushButton_ogrtemail.raise_()
        self.pushButton_ogrtakademisyennumara.raise_()
        self.pushButton_ogrtfakulte.raise_()
        self.pushButton_ogrtisimsoyisim.raise_()
        self.label_ogrtphoto.raise_()
        self.label_profilsar_3.raise_()
        self.groupBox_solmenu = QtWidgets.QGroupBox(Form_akademisyen)
        self.groupBox_solmenu.setGeometry(QtCore.QRect(0, 270, 331, 731))
        self.groupBox_solmenu.setTitle("")
        self.groupBox_solmenu.setObjectName("groupBox_solmenu")
        self.listWidget_menu = QtWidgets.QListWidget(self.groupBox_solmenu)
        self.listWidget_menu.setGeometry(QtCore.QRect(0, 50, 341, 661))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listWidget_menu.setFont(font)
        self.listWidget_menu.setStyleSheet("QListWidget {\n"
"    background-color: rgb(0, 206, 209);\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #6a5acd; /* Orta mor renk */\n"
"    color: white; /* Seçili öğenin metin rengi */\n"
"}\n"
"")
        self.listWidget_menu.setIconSize(QtCore.QSize(36, 36))
        self.listWidget_menu.setObjectName("listWidget_menu")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/gerigel/geridonus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/notgirişi/notgirisi.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/devamsızlık/devamsızlık.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/sifredegistir/sifredegistir2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/sikayetkutusu/sikayetkutusu2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.listWidget_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/cikisyap/cikisyap.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon12)
        self.listWidget_menu.addItem(item)
        self.label = QtWidgets.QLabel(self.groupBox_solmenu)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 206, 209);\n"
"border-image: url(:/arkaplan/ic_arkaplan.jpg);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_amasyalogo = QtWidgets.QLabel(Form_akademisyen)
        self.label_amasyalogo.setGeometry(QtCore.QRect(0, 0, 331, 201))
        self.label_amasyalogo.setStyleSheet("image: url(:/amasyaunipng/amasyauni.png);\n"
"border-image: url(:/arkaplan/ic_arkaplan.jpg);")
        self.label_amasyalogo.setText("")
        self.label_amasyalogo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_amasyalogo.setObjectName("label_amasyalogo")
        self.label_amasyauni = QtWidgets.QLabel(Form_akademisyen)
        self.label_amasyauni.setGeometry(QtCore.QRect(0, 200, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_amasyauni.setFont(font)
        self.label_amasyauni.setStyleSheet("border-image: url(:/arkaplan/ic_arkaplan.jpg);")
        self.label_amasyauni.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amasyauni.setObjectName("label_amasyauni")
        self.groupBox_notgirisi = QtWidgets.QGroupBox(Form_akademisyen)
        self.groupBox_notgirisi.setGeometry(QtCore.QRect(350, 0, 1241, 1000))
        self.groupBox_notgirisi.setTitle("")
        self.groupBox_notgirisi.setObjectName("groupBox_notgirisi")
        self.label_notgirisi = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_notgirisi.setGeometry(QtCore.QRect(0, 0, 1241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_notgirisi.setFont(font)
        self.label_notgirisi.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_notgirisi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notgirisi.setObjectName("label_notgirisi")
        self.tableWidget_notgir = QtWidgets.QTableWidget(self.groupBox_notgirisi)
        self.tableWidget_notgir.setGeometry(QtCore.QRect(70, 110, 951, 121))
        self.tableWidget_notgir.setStyleSheet("QTableWidget {\n"
"    border: 2px solid #ccc; /* Tablo kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Hücre içeriğinin etrafındaki boşluk */\n"
"    background-color: #f0f0f0; /* Hücre arka plan rengi */\n"
"    border: none; /* Hücre kenarlık stilini kaldırma */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding: 3px; /* Sütun başlığı içeriğinin etrafındaki boşluk */\n"
"    text-align: center; /* Sütun başlığı metni ortala */\n"
"    background-color: #f0f0f0; /* Sütun başlığı arka plan rengi */\n"
"    border: 2px solid #ccc; /* Sütun başlığı kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: lightblue; /* Seçili hücre arka plan rengi */\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget_notgir.setObjectName("tableWidget_notgir")
        self.tableWidget_notgir.setColumnCount(4)
        self.tableWidget_notgir.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_notgir.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_notgir.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_notgir.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_notgir.setItem(0, 3, item)
        self.tableWidget_notgir.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_notgir.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_notgir.verticalHeader().setDefaultSectionSize(60)
        self.tableWidget_notgir.verticalHeader().setMinimumSectionSize(50)
        self.label_blok_2 = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_blok_2.setGeometry(QtCore.QRect(60, 100, 114, 60))
        self.label_blok_2.setText("")
        self.label_blok_2.setObjectName("label_blok_2")
        self.pushButton_notsonuclandir = QtWidgets.QPushButton(self.groupBox_notgirisi)
        self.pushButton_notsonuclandir.setGeometry(QtCore.QRect(1030, 170, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.pushButton_notsonuclandir.setFont(font)
        self.pushButton_notsonuclandir.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 12px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        self.pushButton_notsonuclandir.setObjectName("pushButton_notsonuclandir")
        self.label_bilgilendirme = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_bilgilendirme.setGeometry(QtCore.QRect(0, 580, 1241, 141))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_bilgilendirme.setFont(font)
        self.label_bilgilendirme.setStyleSheet("QLabel {\n"
"    border-radius: 15px; /* Köşeleri daha bombeli yapar */\n"
"    border: 2px solid #ccc; /* Kenarlık çizgisi ekler */\n"
"    padding: 10px; /* Yazı içeriğinin kenarlardan içeriye uzaklığı */\n"
"    font-size: 18px; /* Yazı fontunun boyutu */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #555; /* Yazı rengi */\n"
"    background-color: #f0f0f0; /* Arka plan rengini gri tonlarına ayarlar */\n"
"}\n"
"")
        self.label_bilgilendirme.setObjectName("label_bilgilendirme")
        self.label_blok_profilbilgileri = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_blok_profilbilgileri.setGeometry(QtCore.QRect(53, 350, 24, 131))
        self.label_blok_profilbilgileri.setText("")
        self.label_blok_profilbilgileri.setObjectName("label_blok_profilbilgileri")
        self.tableWidget_notgir_profilbilgileri = QtWidgets.QTableWidget(self.groupBox_notgirisi)
        self.tableWidget_notgir_profilbilgileri.setGeometry(QtCore.QRect(60, 350, 441, 121))
        self.tableWidget_notgir_profilbilgileri.setStyleSheet("QTableWidget {\n"
"    border: 2px solid #ccc; /* Tablo kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Hücre içeriğinin etrafındaki boşluk */\n"
"    background-color: #f0f0f0; /* Hücre arka plan rengi */\n"
"    border: none; /* Hücre kenarlık stilini kaldırma */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding: 3px; /* Sütun başlığı içeriğinin etrafındaki boşluk */\n"
"    text-align: center; /* Sütun başlığı metni ortala */\n"
"    background-color: #f0f0f0; /* Sütun başlığı arka plan rengi */\n"
"    border: 2px solid #ccc; /* Sütun başlığı kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: lightblue; /* Seçili hücre arka plan rengi */\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget_notgir_profilbilgileri.setObjectName("tableWidget_notgir_profilbilgileri")
        self.tableWidget_notgir_profilbilgileri.setColumnCount(2)
        self.tableWidget_notgir_profilbilgileri.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notgir_profilbilgileri.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir_profilbilgileri.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_notgir_profilbilgileri.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_notgir_profilbilgileri.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_notgir_profilbilgileri.setItem(0, 1, item)
        self.tableWidget_notgir_profilbilgileri.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_notgir_profilbilgileri.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget_notgir_profilbilgileri.verticalHeader().setDefaultSectionSize(70)
        self.tableWidget_notgir_profilbilgileri.verticalHeader().setMinimumSectionSize(50)
        self.label_engelnotgirisi = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_engelnotgirisi.setGeometry(QtCore.QRect(720, 320, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_engelnotgirisi.setFont(font)
        self.label_engelnotgirisi.setStyleSheet("QLabel {\n"
"    \n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_engelnotgirisi.setText("")
        self.label_engelnotgirisi.setObjectName("label_engelnotgirisi")
        self.label_engelnotgirisi2 = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_engelnotgirisi2.setGeometry(QtCore.QRect(0, 320, 541, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_engelnotgirisi2.setFont(font)
        self.label_engelnotgirisi2.setStyleSheet("QLabel {\n"
"    \n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_engelnotgirisi2.setText("")
        self.label_engelnotgirisi2.setObjectName("label_engelnotgirisi2")
        self.label_engelnotgirisi3 = QtWidgets.QLabel(self.groupBox_notgirisi)
        self.label_engelnotgirisi3.setGeometry(QtCore.QRect(550, 309, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_engelnotgirisi3.setFont(font)
        self.label_engelnotgirisi3.setStyleSheet("QLabel {\n"
"    font-size: 24px; /* Yazı boyutu */\n"
"    color: #222; /* Koyu renkli yazı rengi */\n"
"}\n"
"")
        self.label_engelnotgirisi3.setObjectName("label_engelnotgirisi3")
        self.tableWidget_notgir_profilbilgileri.raise_()
        self.label_notgirisi.raise_()
        self.tableWidget_notgir.raise_()
        self.label_blok_2.raise_()
        self.pushButton_notsonuclandir.raise_()
        self.label_bilgilendirme.raise_()
        self.label_blok_profilbilgileri.raise_()
        self.label_engelnotgirisi.raise_()
        self.label_engelnotgirisi2.raise_()
        self.label_engelnotgirisi3.raise_()
        self.groupBox_devamsizlik = QtWidgets.QGroupBox(Form_akademisyen)
        self.groupBox_devamsizlik.setGeometry(QtCore.QRect(350, 0, 1241, 1000))
        self.groupBox_devamsizlik.setTitle("")
        self.groupBox_devamsizlik.setObjectName("groupBox_devamsizlik")
        self.label_devamsizlikgirisimenucubugu = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_devamsizlikgirisimenucubugu.setGeometry(QtCore.QRect(0, 0, 1241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_devamsizlikgirisimenucubugu.setFont(font)
        self.label_devamsizlikgirisimenucubugu.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_devamsizlikgirisimenucubugu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devamsizlikgirisimenucubugu.setObjectName("label_devamsizlikgirisimenucubugu")
        self.pushButton_devamsizlikonayla = QtWidgets.QPushButton(self.groupBox_devamsizlik)
        self.pushButton_devamsizlikonayla.setGeometry(QtCore.QRect(840, 190, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.pushButton_devamsizlikonayla.setFont(font)
        self.pushButton_devamsizlikonayla.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 12px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        self.pushButton_devamsizlikonayla.setObjectName("pushButton_devamsizlikonayla")
        self.label_blok = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_blok.setGeometry(QtCore.QRect(60, 110, 133, 69))
        self.label_blok.setText("")
        self.label_blok.setObjectName("label_blok")
        self.tableWidget_devamsizlik = QtWidgets.QTableWidget(self.groupBox_devamsizlik)
        self.tableWidget_devamsizlik.setGeometry(QtCore.QRect(70, 110, 761, 151))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.tableWidget_devamsizlik.setFont(font)
        self.tableWidget_devamsizlik.setStyleSheet("QTableWidget {\n"
"    border: 5px solid #ccc; /* Tablo kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Hücre içeriğinin etrafındaki boşluk */\n"
"    background-color: #f0f0f0; /* Hücre arka plan rengi */\n"
"    border: none; /* Hücre kenarlık stilini kaldırma */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding: 11px; /* Sütun başlığı içeriğinin etrafındaki boşluk */\n"
"    text-align: center; /* Sütun başlığı metni ortala */\n"
"    background-color: #f0f0f0; /* Sütun başlığı arka plan rengi */\n"
"    border: 2px solid #ccc; /* Sütun başlığı kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: lightblue; /* Seçili hücre arka plan rengi */\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget_devamsizlik.setObjectName("tableWidget_devamsizlik")
        self.tableWidget_devamsizlik.setColumnCount(3)
        self.tableWidget_devamsizlik.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_devamsizlik.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_devamsizlik.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_devamsizlik.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_devamsizlik.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_devamsizlik.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_devamsizlik.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_devamsizlik.setItem(0, 2, item)
        self.tableWidget_devamsizlik.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_devamsizlik.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget_devamsizlik.verticalHeader().setDefaultSectionSize(60)
        self.tableWidget_devamsizlik.verticalHeader().setMinimumSectionSize(50)
        self.label_bilgilendirmedevamsizlik = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_bilgilendirmedevamsizlik.setGeometry(QtCore.QRect(0, 580, 1241, 141))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_bilgilendirmedevamsizlik.setFont(font)
        self.label_bilgilendirmedevamsizlik.setStyleSheet("QLabel {\n"
"    border-radius: 15px; /* Köşeleri daha bombeli yapar */\n"
"    border: 2px solid #ccc; /* Kenarlık çizgisi ekler */\n"
"    padding: 10px; /* Yazı içeriğinin kenarlardan içeriye uzaklığı */\n"
"    font-size: 18px; /* Yazı fontunun boyutu */\n"
"    font-weight: bold; /* Yazı fontunu kalın yapar */\n"
"    color: #555; /* Yazı rengi */\n"
"    background-color: #f0f0f0; /* Arka plan rengini gri tonlarına ayarlar */\n"
"}\n"
"")
        self.label_bilgilendirmedevamsizlik.setObjectName("label_bilgilendirmedevamsizlik")
        self.tableWidget_devamsizlikgirprofil = QtWidgets.QTableWidget(self.groupBox_devamsizlik)
        self.tableWidget_devamsizlikgirprofil.setGeometry(QtCore.QRect(60, 350, 441, 121))
        self.tableWidget_devamsizlikgirprofil.setStyleSheet("QTableWidget {\n"
"    border: 2px solid #ccc; /* Tablo kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Hücre içeriğinin etrafındaki boşluk */\n"
"    background-color: #f0f0f0; /* Hücre arka plan rengi */\n"
"    border: none; /* Hücre kenarlık stilini kaldırma */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding: 3px; /* Sütun başlığı içeriğinin etrafındaki boşluk */\n"
"    text-align: center; /* Sütun başlığı metni ortala */\n"
"    background-color: #f0f0f0; /* Sütun başlığı arka plan rengi */\n"
"    border: 2px solid #ccc; /* Sütun başlığı kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: lightblue; /* Seçili hücre arka plan rengi */\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget_devamsizlikgirprofil.setObjectName("tableWidget_devamsizlikgirprofil")
        self.tableWidget_devamsizlikgirprofil.setColumnCount(2)
        self.tableWidget_devamsizlikgirprofil.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_devamsizlikgirprofil.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_devamsizlikgirprofil.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_devamsizlikgirprofil.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_devamsizlikgirprofil.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_devamsizlikgirprofil.setItem(0, 1, item)
        self.tableWidget_devamsizlikgirprofil.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_devamsizlikgirprofil.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget_devamsizlikgirprofil.verticalHeader().setDefaultSectionSize(70)
        self.tableWidget_devamsizlikgirprofil.verticalHeader().setMinimumSectionSize(50)
        self.label_blok_devamsizlikprofil = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_blok_devamsizlikprofil.setGeometry(QtCore.QRect(53, 350, 24, 131))
        self.label_blok_devamsizlikprofil.setText("")
        self.label_blok_devamsizlikprofil.setObjectName("label_blok_devamsizlikprofil")
        self.label_engeldevamsizlilk = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_engeldevamsizlilk.setGeometry(QtCore.QRect(0, 320, 541, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_engeldevamsizlilk.setFont(font)
        self.label_engeldevamsizlilk.setStyleSheet("QLabel {\n"
"    \n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_engeldevamsizlilk.setText("")
        self.label_engeldevamsizlilk.setObjectName("label_engeldevamsizlilk")
        self.label_engeldevamsizlilk3 = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_engeldevamsizlilk3.setGeometry(QtCore.QRect(550, 309, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_engeldevamsizlilk3.setFont(font)
        self.label_engeldevamsizlilk3.setStyleSheet("QLabel {\n"
"    font-size: 24px; /* Yazı boyutu */\n"
"    color: #222; /* Koyu renkli yazı rengi */\n"
"}\n"
"")
        self.label_engeldevamsizlilk3.setObjectName("label_engeldevamsizlilk3")
        self.label_engeldevamsizlilk2 = QtWidgets.QLabel(self.groupBox_devamsizlik)
        self.label_engeldevamsizlilk2.setGeometry(QtCore.QRect(720, 320, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_engeldevamsizlilk2.setFont(font)
        self.label_engeldevamsizlilk2.setStyleSheet("QLabel {\n"
"    \n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_engeldevamsizlilk2.setText("")
        self.label_engeldevamsizlilk2.setObjectName("label_engeldevamsizlilk2")
        self.tableWidget_devamsizlik.raise_()
        self.label_devamsizlikgirisimenucubugu.raise_()
        self.pushButton_devamsizlikonayla.raise_()
        self.label_blok.raise_()
        self.label_bilgilendirmedevamsizlik.raise_()
        self.tableWidget_devamsizlikgirprofil.raise_()
        self.label_blok_devamsizlikprofil.raise_()
        self.label_engeldevamsizlilk.raise_()
        self.label_engeldevamsizlilk3.raise_()
        self.label_engeldevamsizlilk2.raise_()
        self.groupBox_sifredegistir = QtWidgets.QGroupBox(Form_akademisyen)
        self.groupBox_sifredegistir.setGeometry(QtCore.QRect(350, 0, 1241, 1000))
        self.groupBox_sifredegistir.setTitle("")
        self.groupBox_sifredegistir.setObjectName("groupBox_sifredegistir")
        self.label_sifredegismenucubugu = QtWidgets.QLabel(self.groupBox_sifredegistir)
        self.label_sifredegismenucubugu.setGeometry(QtCore.QRect(0, 0, 1241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_sifredegismenucubugu.setFont(font)
        self.label_sifredegismenucubugu.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    background-color: #f0f0f0; /* Arka plan rengi */\n"
"    color: #222; /* Koyu gri metin rengi */\n"
"    padding: 20px; /* İç boşluk */\n"
"    border: 1px solid #ccc; /* Kenarlık */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1); /* Gölge */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Yumuşak geçiş */\n"
"    text-align: center; /* Metni merkezle */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #e0e0e0; /* Arka plan rengi (hover durumunda) */\n"
"    border-color: #999; /* Kenarlık rengi (hover durumunda) */\n"
"}\n"
"")
        self.label_sifredegismenucubugu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sifredegismenucubugu.setObjectName("label_sifredegismenucubugu")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_sifredegistir)
        self.widget_2.setGeometry(QtCore.QRect(240, 200, 741, 461))
        self.widget_2.setStyleSheet("#widget_2 {\n"
"    border: 4px solid #555555; /* Kenarlık rengini ve kalınlığını ayarla */\n"
"    border-radius: 5px; /* Köşeleri yuvarla */\n"
"    padding: 10px; /* İçeriği kenarlardan ayır */\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 50, 581, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_yenisifre1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_yenisifre1.sizePolicy().hasHeightForWidth())
        self.lineEdit_yenisifre1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_yenisifre1.setFont(font)
        self.lineEdit_yenisifre1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_yenisifre1.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #5e72e4; /* Kenarlık rengini değiştirin */\n"
"    border-radius: 15px;  /* Daha yuvarlak kenarlar için değeri artırın */\n"
"    padding: 10px; /* Metin içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 20px; /* Metin fontunun boyutunu biraz daha büyütün */\n"
"    color: #333; /* Metin rengini belirler */\n"
"    background-color: #f8f9fe; /* Arka plan rengini belirler */\n"
"}\n"
"")
        self.lineEdit_yenisifre1.setText("")
        self.lineEdit_yenisifre1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_yenisifre1.setObjectName("lineEdit_yenisifre1")
        self.verticalLayout_3.addWidget(self.lineEdit_yenisifre1)
        self.lineEdit_eskisifre = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_eskisifre.sizePolicy().hasHeightForWidth())
        self.lineEdit_eskisifre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_eskisifre.setFont(font)
        self.lineEdit_eskisifre.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #5e72e4; /* Kenarlık rengini değiştirin */\n"
"    border-radius: 15px;  /* Daha yuvarlak kenarlar için değeri artırın */\n"
"    padding: 10px; /* Metin içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 20px; /* Metin fontunun boyutunu biraz daha büyütün */\n"
"    color: #333; /* Metin rengini belirler */\n"
"    background-color: #f8f9fe; /* Arka plan rengini belirler */\n"
"}\n"
"")
        self.lineEdit_eskisifre.setText("")
        self.lineEdit_eskisifre.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_eskisifre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_eskisifre.setObjectName("lineEdit_eskisifre")
        self.verticalLayout_3.addWidget(self.lineEdit_eskisifre)
        self.lineEdit_yenisifre2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_yenisifre2.sizePolicy().hasHeightForWidth())
        self.lineEdit_yenisifre2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_yenisifre2.setFont(font)
        self.lineEdit_yenisifre2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_yenisifre2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #5e72e4; /* Kenarlık rengini değiştirin */\n"
"    border-radius: 15px;  /* Daha yuvarlak kenarlar için değeri artırın */\n"
"    padding: 10px; /* Metin içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 20px; /* Metin fontunun boyutunu biraz daha büyütün */\n"
"    color: #333; /* Metin rengini belirler */\n"
"    background-color: #f8f9fe; /* Arka plan rengini belirler */\n"
"}\n"
"")
        self.lineEdit_yenisifre2.setText("")
        self.lineEdit_yenisifre2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_yenisifre2.setObjectName("lineEdit_yenisifre2")
        self.verticalLayout_3.addWidget(self.lineEdit_yenisifre2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.checkBox_girisekraninadon = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_girisekraninadon.setGeometry(QtCore.QRect(80, 275, 591, 31))
        self.checkBox_girisekraninadon.setStyleSheet("QCheckBox {\n"
"                spacing: 5px;\n"
"                font-size: 20px;\n"
"                color: #333;\n"
"            }")
        self.checkBox_girisekraninadon.setObjectName("checkBox_girisekraninadon")
        self.pushButton_sifredegistir = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_sifredegistir.setGeometry(QtCore.QRect(80, 315, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.pushButton_sifredegistir.setFont(font)
        self.pushButton_sifredegistir.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/şifredeğiştir/şifredeğiş.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sifredegistir.setIcon(icon13)
        self.pushButton_sifredegistir.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_sifredegistir.setObjectName("pushButton_sifredegistir")
        self.label_sifreguncellendi = QtWidgets.QLabel(self.widget_2)
        self.label_sifreguncellendi.setGeometry(QtCore.QRect(80, 385, 591, 31))
        self.label_sifreguncellendi.setStyleSheet("QLabel {\n"
"    color: #008000; /* Yeşil renk */\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_sifreguncellendi.setText("")
        self.label_sifreguncellendi.setObjectName("label_sifreguncellendi")
        self.groupBox_duyuruyap = QtWidgets.QGroupBox(Form_akademisyen)
        self.groupBox_duyuruyap.setGeometry(QtCore.QRect(350, 0, 1241, 1000))
        self.groupBox_duyuruyap.setTitle("")
        self.groupBox_duyuruyap.setObjectName("groupBox_duyuruyap")
        self.pushButton_gonder = QtWidgets.QPushButton(self.groupBox_duyuruyap)
        self.pushButton_gonder.setGeometry(QtCore.QRect(1010, 640, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.pushButton_gonder.setFont(font)
        self.pushButton_gonder.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        self.pushButton_gonder.setIcon(icon11)
        self.pushButton_gonder.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_gonder.setObjectName("pushButton_gonder")
        self.textEdit_metin = QtWidgets.QTextEdit(self.groupBox_duyuruyap)
        self.textEdit_metin.setGeometry(QtCore.QRect(60, 260, 1101, 351))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.textEdit_metin.setFont(font)
        self.textEdit_metin.setStyleSheet("QTextEdit {\n"
"    border: 2px solid #5e72e4; /* Kenarlık rengini değiştirin */\n"
"    border-radius: 15px;  /* Daha yuvarlak kenarlar için değeri artırın */\n"
"    padding: 10px; /* Metin içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 18px; /* Metin fontunun boyutunu biraz daha büyütün */\n"
"    color: #333; /* Metin rengini belirler */\n"
"    background-color: #f8f9fe; /* Arka plan rengini belirler */\n"
"}\n"
"QTextEdit QScrollBar {\n"
"    width: 0px;                 /* Yatay ve dikey scroll bar genişliği */\n"
"    height: 0px;                /* Yatay ve dikey scroll bar yüksekliği */\n"
"    background: transparent;    /* Scroll bar arka plan rengi */\n"
"}\n"
"")
        self.textEdit_metin.setObjectName("textEdit_metin")
        self.lineEdit_baslik = QtWidgets.QLineEdit(self.groupBox_duyuruyap)
        self.lineEdit_baslik.setGeometry(QtCore.QRect(60, 180, 801, 51))
        self.lineEdit_baslik.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #5e72e4; /* Kenarlık rengini değiştirin */\n"
"    border-radius: 15px;  /* Daha yuvarlak kenarlar için değeri artırın */\n"
"    padding: 10px; /* Metin içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 22px; /* Metin fontunun boyutunu biraz daha büyütün */\n"
"    color: #333; /* Metin rengini belirler */\n"
"    background-color: #f8f9fe; /* Arka plan rengini belirler */\n"
"}\n"
"\n"
"")
        self.lineEdit_baslik.setObjectName("lineEdit_baslik")
        self.label_devamsizlikgirisimenucubugu_2 = QtWidgets.QLabel(self.groupBox_duyuruyap)
        self.label_devamsizlikgirisimenucubugu_2.setGeometry(QtCore.QRect(0, 0, 1241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_devamsizlikgirisimenucubugu_2.setFont(font)
        self.label_devamsizlikgirisimenucubugu_2.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_devamsizlikgirisimenucubugu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_devamsizlikgirisimenucubugu_2.setObjectName("label_devamsizlikgirisimenucubugu_2")
        self.label_bilgi = QtWidgets.QLabel(self.groupBox_duyuruyap)
        self.label_bilgi.setGeometry(QtCore.QRect(60, 630, 551, 31))
        self.label_bilgi.setText("")
        self.label_bilgi.setObjectName("label_bilgi")
        self.pushButton_gonder.raise_()
        self.textEdit_metin.raise_()
        self.label_devamsizlikgirisimenucubugu_2.raise_()
        self.lineEdit_baslik.raise_()
        self.label_bilgi.raise_()
        self.label_amasyalogo.raise_()
        self.label_amasyauni.raise_()
        self.groupBox_solmenu.raise_()
        self.groupBox_anamenu.raise_()
        self.groupBox_sifredegistir.raise_()
        self.groupBox_notgirisi.raise_()
        self.groupBox_devamsizlik.raise_()
        self.groupBox_duyuruyap.raise_()

        self.retranslateUi(Form_akademisyen)
        QtCore.QMetaObject.connectSlotsByName(Form_akademisyen)

    def retranslateUi(self, Form_akademisyen):
        _translate = QtCore.QCoreApplication.translate
        Form_akademisyen.setWindowTitle(_translate("Form_akademisyen", "Akademisyen"))
        self.pushButton_verilendersler.setText(_translate("Form_akademisyen", "Aktif Dönemde Verilen Dersler"))
        self.pushButton_dersgorenogrenc.setText(_translate("Form_akademisyen", "Aktif Dönemde Ders Gören Öğrenciler"))
        self.pushButton_ogrtemail.setText(_translate("Form_akademisyen", "e-mail"))
        self.pushButton_ogrtakademisyennumara.setText(_translate("Form_akademisyen", "Akademisyen Numarası:"))
        self.label_profil.setText(_translate("Form_akademisyen", " Profil"))
        self.pushButton_ogrtfakulte.setText(_translate("Form_akademisyen", "Mühendislik Fakültesi"))
        self.pushButton_ogrtisimsoyisim.setText(_translate("Form_akademisyen", "İsim Soyisim"))
        self.listWidget_menu.setWhatsThis(_translate("Form_akademisyen", "<html><head/><body><p><br/></p></body></html>"))
        __sortingEnabled = self.listWidget_menu.isSortingEnabled()
        self.listWidget_menu.setSortingEnabled(False)
        item = self.listWidget_menu.item(0)
        item.setText(_translate("Form_akademisyen", "Ana Menü"))
        item = self.listWidget_menu.item(1)
        item.setText(_translate("Form_akademisyen", "Not Girişi"))
        item = self.listWidget_menu.item(2)
        item.setText(_translate("Form_akademisyen", "Devamsızlık Girişi"))
        item = self.listWidget_menu.item(3)
        item.setText(_translate("Form_akademisyen", "Şifre Değiştir"))
        item = self.listWidget_menu.item(4)
        item.setText(_translate("Form_akademisyen", "Duyuru Yap"))
        item = self.listWidget_menu.item(5)
        item.setText(_translate("Form_akademisyen", "Çıkış Yap"))
        self.listWidget_menu.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form_akademisyen", "Akademisyen Bilgi Sistemi"))
        self.label_amasyauni.setText(_translate("Form_akademisyen", "AMASYA ÜNİVERSİTESİ"))
        self.label_notgirisi.setText(_translate("Form_akademisyen", "Not Girişi"))
        item = self.tableWidget_notgir.verticalHeaderItem(0)
        item.setText(_translate("Form_akademisyen", "Bilgiler"))
        item = self.tableWidget_notgir.horizontalHeaderItem(0)
        item.setText(_translate("Form_akademisyen", "Öğrenci No"))
        item = self.tableWidget_notgir.horizontalHeaderItem(1)
        item.setText(_translate("Form_akademisyen", "Ders Kodu"))
        item = self.tableWidget_notgir.horizontalHeaderItem(2)
        item.setText(_translate("Form_akademisyen", "Vize Notu"))
        item = self.tableWidget_notgir.horizontalHeaderItem(3)
        item.setText(_translate("Form_akademisyen", "Final Notu"))
        __sortingEnabled = self.tableWidget_notgir.isSortingEnabled()
        self.tableWidget_notgir.setSortingEnabled(False)
        self.tableWidget_notgir.setSortingEnabled(__sortingEnabled)
        self.pushButton_notsonuclandir.setText(_translate("Form_akademisyen", "Sonuçlandır"))
        self.label_bilgilendirme.setText(_translate("Form_akademisyen", "Eğer vize ve final notları girilmiş ancak sonuçlandırma yapılmamışsa,kullanıcı şu mesajı görecek:\n"
"\"Sonuçlandırılmadı.\"Ortalama ve durum bilgilerinin görünebilmesi içinde Sonuçlandır butonuna basılması gerekir."))
        item = self.tableWidget_notgir_profilbilgileri.horizontalHeaderItem(0)
        item.setText(_translate("Form_akademisyen", "Öğrenci No"))
        item = self.tableWidget_notgir_profilbilgileri.horizontalHeaderItem(1)
        item.setText(_translate("Form_akademisyen", "Adı Soyadı"))
        __sortingEnabled = self.tableWidget_notgir_profilbilgileri.isSortingEnabled()
        self.tableWidget_notgir_profilbilgileri.setSortingEnabled(False)
        self.tableWidget_notgir_profilbilgileri.setSortingEnabled(__sortingEnabled)
        self.label_engelnotgirisi3.setText(_translate("Form_akademisyen", "Öğrenci Profili"))
        self.label_devamsizlikgirisimenucubugu.setText(_translate("Form_akademisyen", "Devamsızlık Girişi"))
        self.pushButton_devamsizlikonayla.setText(_translate("Form_akademisyen", "Onayla"))
        item = self.tableWidget_devamsizlik.verticalHeaderItem(0)
        item.setText(_translate("Form_akademisyen", "Bilgiler"))
        item = self.tableWidget_devamsizlik.horizontalHeaderItem(0)
        item.setText(_translate("Form_akademisyen", "Öğrenci No"))
        item = self.tableWidget_devamsizlik.horizontalHeaderItem(1)
        item.setText(_translate("Form_akademisyen", "Ders Kodu"))
        item = self.tableWidget_devamsizlik.horizontalHeaderItem(2)
        item.setText(_translate("Form_akademisyen", "Tarih"))
        __sortingEnabled = self.tableWidget_devamsizlik.isSortingEnabled()
        self.tableWidget_devamsizlik.setSortingEnabled(False)
        self.tableWidget_devamsizlik.setSortingEnabled(__sortingEnabled)
        self.label_bilgilendirmedevamsizlik.setText(_translate("Form_akademisyen", "Her bir devamsızlık tarihi girildiğinde, öğrencinin toplam devamsızlık sayısı bir bir artacak.\n"
"Öğrenci, \"Öğrenci Devamsızlık Durumu\" menüsünden toplam devamsızlık sayısını görebilecek."))
        item = self.tableWidget_devamsizlikgirprofil.horizontalHeaderItem(0)
        item.setText(_translate("Form_akademisyen", "Öğrenci No"))
        item = self.tableWidget_devamsizlikgirprofil.horizontalHeaderItem(1)
        item.setText(_translate("Form_akademisyen", "Adı Soyadı"))
        __sortingEnabled = self.tableWidget_devamsizlikgirprofil.isSortingEnabled()
        self.tableWidget_devamsizlikgirprofil.setSortingEnabled(False)
        self.tableWidget_devamsizlikgirprofil.setSortingEnabled(__sortingEnabled)
        self.label_engeldevamsizlilk3.setText(_translate("Form_akademisyen", "Öğrenci Profili"))
        self.label_sifredegismenucubugu.setText(_translate("Form_akademisyen", "Şifre Değiştir"))
        self.checkBox_girisekraninadon.setText(_translate("Form_akademisyen", "Tüm cihazlardan çıkış yapın"))
        self.pushButton_sifredegistir.setText(_translate("Form_akademisyen", "Şifreyi Değiştir"))
        self.pushButton_gonder.setText(_translate("Form_akademisyen", "Gönder"))
        self.label_devamsizlikgirisimenucubugu_2.setText(_translate("Form_akademisyen", "Duyuru Yap"))
import ikonlar_ogrenci_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_akademisyen = QtWidgets.QWidget()
    ui = Ui_Form_akademisyen()
    ui.setupUi(Form_akademisyen)
    Form_akademisyen.show()
    sys.exit(app.exec_())
