# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ogrenci_isleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/amasyauniico/amasyauni.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(207, 207, 207);")
        self.groupBox_tablo = QtWidgets.QGroupBox(Form)
        self.groupBox_tablo.setGeometry(QtCore.QRect(0, 0, 1600, 1000))
        self.groupBox_tablo.setStyleSheet("#GroupBox {\n"
"    color: rgb(85, 255, 0);\n"
"}\n"
"")
        self.groupBox_tablo.setTitle("")
        self.groupBox_tablo.setObjectName("groupBox_tablo")
        self.label_3 = QtWidgets.QLabel(self.groupBox_tablo)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 36, 49))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setStyleSheet("QLabel {\n"
"    border: none;        /* Çerçevesiz */\n"
"    border-radius: 0;   /* Köşeleri yuvarlatma */\n"
"}\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_bilgilendirme_2 = QtWidgets.QLabel(self.groupBox_tablo)
        self.label_bilgilendirme_2.setGeometry(QtCore.QRect(40, 880, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_bilgilendirme_2.setFont(font)
        self.label_bilgilendirme_2.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    border: none; /* Çerçeveyi kaldırmak için */\n"
"    color: darkgreen;\n"
"}\n"
"")
        self.label_bilgilendirme_2.setText("")
        self.label_bilgilendirme_2.setObjectName("label_bilgilendirme_2")
        self.DateEdit_tarih = QtWidgets.QDateEdit(self.groupBox_tablo)
        self.DateEdit_tarih.setGeometry(QtCore.QRect(1410, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.DateEdit_tarih.setFont(font)
        self.DateEdit_tarih.setStyleSheet("QDateEdit {\n"
"    border: 2px solid #5e72e4; /* Kenarlık rengini değiştirin */\n"
"    border-radius: 15px;  /* Daha yuvarlak kenarlar için değeri artırın */\n"
"    padding: 5px; /* Metin içeriğinin kenarlardan içeriye olan uzaklığını belirler */\n"
"    font-size: 18px; /* Metin fontunun boyutunu biraz daha büyütün */\n"
"    color: #333; /* Metin rengini belirler */\n"
"    background-color: #f8f9fe; /* Arka plan rengini belirler */\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    width: 0px;  /* Açılır pencereyi gösteren oku gizler */\n"
"    height: 0px;\n"
"}\n"
"QDateEdit::down-arrow {\n"
"    image: url(none);  /* Aşağı oku gizler */\n"
"}\n"
"QDateEdit::up-arrow {\n"
"    image: url(none);  /* Yukarı oku gizler */\n"
"}")
        self.DateEdit_tarih.setAlignment(QtCore.Qt.AlignCenter)
        self.DateEdit_tarih.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.DateEdit_tarih.setTimeSpec(QtCore.Qt.LocalTime)
        self.DateEdit_tarih.setObjectName("DateEdit_tarih")
        self.tableWidget_tablo = QtWidgets.QTableWidget(self.groupBox_tablo)
        self.tableWidget_tablo.setGeometry(QtCore.QRect(40, 80, 1591, 781))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_tablo.setFont(font)
        self.tableWidget_tablo.setStyleSheet("QTableWidget {\n"
"    border: 2px solid #ccc; /* Tablo kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Hücre içeriğinin etrafındaki boşluk */\n"
"    background-color: #f0f0f0; /* Hücre arka plan rengi */\n"
"    border: none; /* Hücre kenarlık stilini kaldırma */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding: 3px; /* Sütun başlığı içeriğinin etrafındaki boşluk */\n"
"    text-align: center; /* Sütun başlığı metni ortala */\n"
"    background-color: #f0f0f0; /* Sütun başlığı arka plan rengi */\n"
"    border: 2px solid #ccc; /* Sütun başlığı kenarlık rengi ve kalınlığı */\n"
"    border-radius: 5px; /* Kenar yuvarlaklığı */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: lightblue; /* Seçili hücre arka plan rengi */\n"
"}\n"
"\n"
"\n"
"")
        self.tableWidget_tablo.setObjectName("tableWidget_tablo")
        self.tableWidget_tablo.setColumnCount(9)
        self.tableWidget_tablo.setRowCount(31)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget_tablo.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_tablo.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tablo.setItem(5, 3, item)
        self.tableWidget_tablo.horizontalHeader().setDefaultSectionSize(165)
        self.pushButton_ogruyeekrani = QtWidgets.QPushButton(self.groupBox_tablo)
        self.pushButton_ogruyeekrani.setGeometry(QtCore.QRect(1190, 890, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ogruyeekrani.setFont(font)
        self.pushButton_ogruyeekrani.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        self.pushButton_ogruyeekrani.setObjectName("pushButton_ogruyeekrani")
        self.pushButton_ogrsil = QtWidgets.QPushButton(self.groupBox_tablo)
        self.pushButton_ogrsil.setGeometry(QtCore.QRect(1390, 890, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ogrsil.setFont(font)
        self.pushButton_ogrsil.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        self.pushButton_ogrsil.setObjectName("pushButton_ogrsil")
        self.label_2 = QtWidgets.QLabel(self.groupBox_tablo)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 60, 54))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_notgirisi_6 = QtWidgets.QLabel(self.groupBox_tablo)
        self.label_notgirisi_6.setGeometry(QtCore.QRect(240, 40, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_notgirisi_6.setFont(font)
        self.label_notgirisi_6.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_notgirisi_6.setText("")
        self.label_notgirisi_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notgirisi_6.setObjectName("label_notgirisi_6")
        self.label_notgirisi_7 = QtWidgets.QLabel(self.groupBox_tablo)
        self.label_notgirisi_7.setGeometry(QtCore.QRect(990, 40, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_notgirisi_7.setFont(font)
        self.label_notgirisi_7.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_notgirisi_7.setText("")
        self.label_notgirisi_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notgirisi_7.setObjectName("label_notgirisi_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_tablo)
        self.label_7.setGeometry(QtCore.QRect(720, 20, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_cikis = QtWidgets.QPushButton(self.groupBox_tablo)
        self.pushButton_cikis.setGeometry(QtCore.QRect(40, 900, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.pushButton_cikis.setFont(font)
        self.pushButton_cikis.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cikisyap/cikisyap.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cikis.setIcon(icon1)
        self.pushButton_cikis.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_cikis.setObjectName("pushButton_cikis")
        self.groupBox_kayit = QtWidgets.QGroupBox(Form)
        self.groupBox_kayit.setGeometry(QtCore.QRect(0, 0, 1600, 1000))
        self.groupBox_kayit.setStyleSheet("#GroupBox {\n"
"    \n"
"    color: rgb(0, 255, 127);\n"
"}\n"
"")
        self.groupBox_kayit.setTitle("")
        self.groupBox_kayit.setObjectName("groupBox_kayit")
        self.label = QtWidgets.QLabel(self.groupBox_kayit)
        self.label.setGeometry(QtCore.QRect(710, 8, 201, 171))
        self.label.setStyleSheet("border-image: url(:/amasyaunipng/amasyauni.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_kayit)
        self.frame_2.setGeometry(QtCore.QRect(500, 230, 601, 751))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border: 2px solid #787878; /* Daha koyu gri kenarlık */\n"
"    border-radius: 8px; /* Kenarların yuvarlaklaştırılması */\n"
"    padding: 5px; /* İçerikten kenarlara boşluk */\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 70, 421, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.lineEdit_ad = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ad.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_ad.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_ad.setText("")
        self.lineEdit_ad.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ad.setObjectName("lineEdit_ad")
        self.horizontalLayout_6.addWidget(self.lineEdit_ad)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(200, 0))
        self.label_16.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.lineEdit_soyad = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_soyad.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_soyad.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_soyad.setText("")
        self.lineEdit_soyad.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_soyad.setObjectName("lineEdit_soyad")
        self.horizontalLayout_9.addWidget(self.lineEdit_soyad)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(200, 0))
        self.label_17.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.lineEdit_ogrencino = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ogrencino.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_ogrencino.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_ogrencino.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ogrencino.setObjectName("lineEdit_ogrencino")
        self.horizontalLayout_10.addWidget(self.lineEdit_ogrencino)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_sifre.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_sifre.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_sifre.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.horizontalLayout_5.addWidget(self.lineEdit_sifre)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(200, 0))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.lineEdit_telefonno = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_telefonno.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_telefonno.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_telefonno.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_telefonno.setObjectName("lineEdit_telefonno")
        self.horizontalLayout_7.addWidget(self.lineEdit_telefonno)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(200, 0))
        self.label_9.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit_eposta = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_eposta.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_eposta.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_eposta.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_eposta.setObjectName("lineEdit_eposta")
        self.horizontalLayout_2.addWidget(self.lineEdit_eposta)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.lineEdit_fakulte = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_fakulte.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_fakulte.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_fakulte.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fakulte.setObjectName("lineEdit_fakulte")
        self.horizontalLayout_8.addWidget(self.lineEdit_fakulte)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(200, 0))
        self.label_18.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.lineEdit_bolum = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_bolum.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_bolum.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_bolum.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_bolum.setObjectName("lineEdit_bolum")
        self.horizontalLayout_11.addWidget(self.lineEdit_bolum)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(200, 0))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #f2f2f2; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 10px; /* Kenar yuvarlaklığı */\n"
"    padding: 8px; /* Etiket içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEdit_sinif = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_sinif.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_sinif.setStyleSheet("QLineEdit {\n"
"    color: #333333; /* Metin rengi */\n"
"    background-color: #ffffff; /* Arka plan rengi */\n"
"    border: 2px solid #8c8c8c; /* Kenarlık */\n"
"    border-radius: 8px; /* Kenar yuvarlaklığı */\n"
"    padding: 4px; /* Metin alanı içi boşluk */\n"
"    font-family: Arial; /* Yazı tipi ailesi */\n"
"    font-size: 14px; /* Yazı tipi boyutu */\n"
"    font-weight: bold; /* Yazı tipi kalınlığı */\n"
"}\n"
"")
        self.lineEdit_sinif.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sinif.setObjectName("lineEdit_sinif")
        self.horizontalLayout.addWidget(self.lineEdit_sinif)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_onayla = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_onayla.setGeometry(QtCore.QRect(340, 650, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.pushButton_onayla.setFont(font)
        self.pushButton_onayla.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/onayla/onayla.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_onayla.setIcon(icon2)
        self.pushButton_onayla.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_onayla.setObjectName("pushButton_onayla")
        self.pushButton_geridon = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_geridon.setGeometry(QtCore.QRect(170, 650, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.pushButton_geridon.setFont(font)
        self.pushButton_geridon.setStyleSheet("QPushButton {\n"
"    border: 2px solid #a9a9a9;\n"
"    border-radius: 15px;\n"
"    background-color: #add8e6; /* Açık mavi tonu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88b8d6; /* Biraz daha koyu mavi tonu */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/gerigel/geri dön.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_geridon.setIcon(icon3)
        self.pushButton_geridon.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_geridon.setObjectName("pushButton_geridon")
        self.label_bilgilendirme = QtWidgets.QLabel(self.frame_2)
        self.label_bilgilendirme.setGeometry(QtCore.QRect(110, 610, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_bilgilendirme.setFont(font)
        self.label_bilgilendirme.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    border: none; /* Çerçeveyi kaldırmak için */\n"
"    color: maroon;\n"
"}\n"
"")
        self.label_bilgilendirme.setText("")
        self.label_bilgilendirme.setObjectName("label_bilgilendirme")
        self.label_notgirisi_2 = QtWidgets.QLabel(self.groupBox_kayit)
        self.label_notgirisi_2.setGeometry(QtCore.QRect(0, 190, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_notgirisi_2.setFont(font)
        self.label_notgirisi_2.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_notgirisi_2.setText("")
        self.label_notgirisi_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notgirisi_2.setObjectName("label_notgirisi_2")
        self.label_notgirisi_3 = QtWidgets.QLabel(self.groupBox_kayit)
        self.label_notgirisi_3.setGeometry(QtCore.QRect(1020, 190, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_notgirisi_3.setFont(font)
        self.label_notgirisi_3.setStyleSheet("QLabel {\n"
"    border-image: url(:/arkaplan/ic_arkaplan.jpg);\n"
"    color: #222; /* Yazı rengi */\n"
"    background-color: #f5f5f5; /* Yumuşak bir gri tonu */\n"
"    border: 2px solid #bbb; /* Kenarlık */\n"
"    border-radius: 0px; /* Kenar yuvarlaklığı kaldırıldı */\n"
"    padding: 10px; /* İç boşluk */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #ddd; /* Fare üzerine gelindiğinde arka plan rengi */\n"
"}\n"
"")
        self.label_notgirisi_3.setText("")
        self.label_notgirisi_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notgirisi_3.setObjectName("label_notgirisi_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_kayit)
        self.label_4.setGeometry(QtCore.QRect(600, 180, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_kayit.raise_()
        self.groupBox_tablo.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Öğrenci İşleri"))
        item = self.tableWidget_tablo.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget_tablo.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget_tablo.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget_tablo.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget_tablo.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget_tablo.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget_tablo.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget_tablo.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget_tablo.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget_tablo.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget_tablo.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget_tablo.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget_tablo.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget_tablo.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget_tablo.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget_tablo.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget_tablo.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget_tablo.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget_tablo.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget_tablo.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget_tablo.verticalHeaderItem(20)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget_tablo.verticalHeaderItem(21)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget_tablo.verticalHeaderItem(22)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget_tablo.verticalHeaderItem(23)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget_tablo.verticalHeaderItem(24)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget_tablo.verticalHeaderItem(25)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget_tablo.verticalHeaderItem(26)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget_tablo.verticalHeaderItem(27)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget_tablo.verticalHeaderItem(28)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget_tablo.verticalHeaderItem(29)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget_tablo.verticalHeaderItem(30)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget_tablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Adı"))
        item = self.tableWidget_tablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Soyadı"))
        item = self.tableWidget_tablo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Öğrenci No"))
        item = self.tableWidget_tablo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Şifre"))
        item = self.tableWidget_tablo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Telefon No"))
        item = self.tableWidget_tablo.horizontalHeaderItem(5)
        item.setText(_translate("Form", "E-Posta"))
        item = self.tableWidget_tablo.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Fakülte"))
        item = self.tableWidget_tablo.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Bölüm"))
        item = self.tableWidget_tablo.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Sınıf"))
        __sortingEnabled = self.tableWidget_tablo.isSortingEnabled()
        self.tableWidget_tablo.setSortingEnabled(False)
        self.tableWidget_tablo.setSortingEnabled(__sortingEnabled)
        self.pushButton_ogruyeekrani.setText(_translate("Form", "Öğrenci Ekle"))
        self.pushButton_ogrsil.setText(_translate("Form", "Öğrenci Sil"))
        self.label_7.setText(_translate("Form", "Öğrenci Bilgileri"))
        self.pushButton_cikis.setText(_translate("Form", "Çıkış Yap"))
        self.label_13.setText(_translate("Form", "Adı"))
        self.label_16.setText(_translate("Form", "Soyadı"))
        self.label_17.setText(_translate("Form", "Öğrenci No"))
        self.label_12.setText(_translate("Form", "Şifre"))
        self.label_14.setText(_translate("Form", "Telefon No"))
        self.label_9.setText(_translate("Form", "E-Posta"))
        self.label_15.setText(_translate("Form", "Fakülte"))
        self.label_18.setText(_translate("Form", "Bölüm"))
        self.label_8.setText(_translate("Form", "Sınıf"))
        self.pushButton_onayla.setText(_translate("Form", "Onayla"))
        self.pushButton_geridon.setText(_translate("Form", "Geri Dön"))
        self.label_4.setText(_translate("Form", "Amasya Üniversitesi Öğrenci Kayıt Ekranı"))
import ikonlar_ogrenci_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
